spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: '0825'